export const CHARACTERS_TYPES = {
  REQUEST_CHARACTERS: 'REQUEST_CHARACTERS',
  REQUEST_CHARS_SUCCESS: 'REQUEST_CHARS_SUCCESS',
}

export const GENERAL_ACTIONS = {
  FAILED_TO_REQUEST: 'FAILED_TO_REQUEST',
}

export const HOMEWORLDS_TYPE = {
  REQUEST_HOMEWORLD: 'REQUEST_HOMEWORLD',
  REQUEST_HOMEWORLD_SUCCESS: 'REQUEST_HOMEWORLD_SUCCESS',
}
